# Generated by Django 3.2.4 on 2021-06-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210621_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='std_address',
            new_name='student_address',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='std_course',
            new_name='student_course',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='std_email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='std_mobile',
            new_name='student_mobile',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='std_name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='std_semester',
            new_name='student_semester',
        ),
    ]
